### PR TITLE
Update actions in GitHub Actions workflows

### PR DESCRIPTION
**Pull request by MGaetan89**
This PR updates the various actions used in the existing GitHub Actions workflows:
- `ubuntu-18.04` → `ubuntu-latest`
- `actions/checkout@v1` → `v4`
- `actions/checkout@v2` → `v4`
- `actions/setup-java@v1` → `v4`
- `eskatos/gradle-command-action@v1` → `gradle/actions/setup-gradle@v4`
- `actions/upload-artifact@v1` → `v4`

### CODE REVIEW

**Comment by MGaetan89** [comment]
The Gradle Wrapper jar seemed to not match the Gradle version. So I've ran `./gradlew wrapper --gradle-version=8.2` to redownload it and pushed the changes in https://github.com/premnirmal/StockTicker/pull/382/commits/5b726e6b5827945504117ea9a884ae105b78e847

**Comment by MGaetan89** [comment]
`app/build.gradle` needs access to the Git tags:
https://github.com/premnirmal/StockTicker/blob/9a303582c0be12264c7bc95cdcb821e523712995/app/build.gradle#L34-L41

So I've enabled fetching the Git tags in `unit-tests.yml` in https://github.com/premnirmal/StockTicker/pull/382/commits/6d79dbec66e245b647e80c3bbe2e6a0a24c690ff

**Comment by premnirmal** [comment]
> `app/build.gradle` needs access to the Git tags:
> 
> https://github.com/premnirmal/StockTicker/blob/9a303582c0be12264c7bc95cdcb821e523712995/app/build.gradle#L34-L41
> 
> So I've enabled fetching the Git tags in `unit-tests.yml` in [6d79dbe](https://github.com/premnirmal/StockTicker/commit/6d79dbec66e245b647e80c3bbe2e6a0a24c690ff)

Not sure if the unit test build failure (process 'git' failure) is due to the change in ubuntu version?

**Comment by MGaetan89** [comment]
Ok, fetching the tags is not enough, so I've enabled fetching the Git history in https://github.com/premnirmal/StockTicker/pull/382/commits/bf9e86ac9161ca5874c765a8c1cc0dc69b08cc52

**Comment by MGaetan89** [comment]
> > `app/build.gradle` needs access to the Git tags:
> > https://github.com/premnirmal/StockTicker/blob/9a303582c0be12264c7bc95cdcb821e523712995/app/build.gradle#L34-L41
> > 
> > So I've enabled fetching the Git tags in `unit-tests.yml` in [6d79dbe](https://github.com/premnirmal/StockTicker/commit/6d79dbec66e245b647e80c3bbe2e6a0a24c690ff)
> 
> Not sure if the unit test build failure (process 'git' failure) is due to the change in ubuntu version?

I've tried fetching the Git history, like in `build.yml`. Let's see if that works 🤞🏻

**Pull request merged**
