### PR TITLE
Add alerts and notes

### PR DESCRIPTION
**Pull request by premnirmal**
@jurgen178 this is based on your PR #139 , plus some tweaks and updates to it

### CODE REVIEW

**Comment by jurgen178** [comment]
Thanks @premnirmal , one question: The generic alert for 10% or higher does not reset. Quite often stocks stays at larger changes for quite some time during the day and would result in a lot of notifications for each update.

**Comment by premnirmal** [comment]
That's a good point @jurgen178. I think if the notification ID is constant per ticker then we won't see multiple notifications, instead the same notification will be updated. I'll see if that works

**Comment by jurgen178** [comment]
@premnirmal I was wondering if adding the number of days to the hashed quote symbol could actually reset the notification to be send again the next day? Having a notification for a large change for the next trading day with the same stock symbol would be good, right?

**Comment by jurgen178** [comment]
Is it possible to have a pin on the new total holdings display to keep always on top? Or a setting maybe?
I think the button in the head display is very nicely done, it is just that for myself I like to have as much as possible on display all the time. I would prefer one huge dashboard with tiny font over any other solution in general. I have played around with the compact display mode and I like it even more than in the beginning.

**Comment by premnirmal** [comment]
About the number of days - adding that to the hash will make the notification ID unique per day, but it may lead to many notifications eg a user will see 2 notifications for the same symbol, one displayed today and one tomorrow. Maybe it will require removing the previous day's notification

**Comment by jurgen178** [comment]
@premnirmal I have translations for german ready, but I cannot make a PR because of permissions. 
I have updated my [branch](https://github.com/jurgen178/StockTicker/tree/add-alerts/app/src/main/res/values-de), please take the resource files from there.

**Comment by premnirmal** [comment]
Picked the german translations 👍

**Pull request merged**
