### PR TITLE
Add 1 day range

### PR DESCRIPTION
**Pull request by b0bdN**
Hi,

Like in the issue #87, I like to see the chart of the day to see what's happening.
I added the button **1D** below the charts.

StockTicker_1dRange

I checked the chart of some actions and the result correspond to the reality.
I don't know what's going to happen on the day of the exchange. We'll see on Monday. :)

### CODE REVIEW

**Comment by b0bdN** [comment]
[Update]:
Here are the two screenshots for the 1D range of today:
**GOOG 12AM**
StockTicker_1D_12AM

**GOOG 3PM**
StockTicker_1D_3PM

It looks like that the chart is good :)

[Enhancement]: Add time values instead of the date.

**Comment by b0bdN** [comment]
I set the 1D Range by default when looking at a symbol.

**Comment by premnirmal** [comment]
Looks good, please keep the changes separate. I will merge your PRs once they are updated

**Comment by premnirmal** [comment]
Code looks good to me. I think you missed the portuguese translation here :)

**Comment by b0bdN** [comment]
Done! :-)

**Comment by premnirmal** [comment]
Thanks!

**Review by premnirmal — APPROVED** [review]

**Pull request merged**
